### PR TITLE
Added Maven BND plugin to generate of OSGi header in Manifest

### PR DESCRIPTION
**Pull request by siepkes**
I've made changes to the POM to have Maven generate OSGi headers. This way the addon can be used in an Vaadin OSGi project.

### CODE REVIEW

**Comment by siepkes** [comment]
@henrikerola Do you need me to make changes in order for this to get merged?

**Comment by henrikerola** [comment]
I will test the PR as soon as possible and also release a new version of the addon.

**Comment by siepkes** [comment]
@henrikerola Thanks for merging it! Really useful plugin!

**Comment by henrikerola** [comment]
Thanks a lot for the pull request, I need to learn some OSGi ;)

**Pull request merged**
